### ISSUE TITLE
Migrate from MongoDB to Cloud Firestore

### ISSUE THREAD

**Issue by NickBurnett** [acmutd/acm-bot#29]
There's no incentive to keep data storage for Circles and other information on the Compute Engine. Instead, we'll store everything in the cloud to dockerize the bot and make it less dependent on local filesystem resources.

**Comment by NickBurnett** [comment]
This will have a heavy refactor in the code (not a cleanup, but a complete overhaul of the underlying database system) since moving from MongoDB to Firebase isn't trivial. Hopefully, this will be much more scalable than the current system since the database isn't a local MongoDB instance running on Compute Engine.

**Comment by legitatx** [comment]
I got this! ;)

**Comment by NickBurnett** [comment]
Talk to @WillieCubed about getting access to our GCP project. Currently, the database is hosted locally on Compute Engine. It would be very bad if that database got deleted before the bot gets updated, so just make sure that your CRUD is isolated to reads :D

**Comment by legitatx** [comment]
> Talk to @WillieCubed about getting access to our GCP project. Currently, the database is hosted locally on Compute Engine. It would be very bad if that database got deleted before the bot gets updated, so just make sure that your CRUD is isolated to reads :D

Sounds gucci

**Comment by WillieCubed** [comment]
@NickBurnett Was this resolved with #28 or #36?

**Comment by NickBurnett** [comment]
@WillieCubed No, the migration isn't even close as far as I know, although I do believe that, after some discussion with @Stevenmqnguyen about the state of the portal backend, I actually think sticking with MongoDB and just getting rid of the local Compute Engine instance is probably the move.

**Comment by NickBurnett** [comment]
@WillieCubed Not necessarily in the near-term (1-2 weeks) since I believe most of the data has to be migrated manually. Long-term, though, it definitely makes sense to use the ACM Core infrastructure to make sure all of ACM's data is converged to a single place, avoiding to need to scavenge for bits of data here-and-there. I'll have a talk with @ez314 about his thoughts later this week, and I'll get back to you.

**Comment by ez314** [comment]
Agree on consolidation for benefit of having unified data storage. Unsure about the idea of cost savings from not running MongoDB on CE. Cost savings more likely to come from getting something smaller but bursts well (during compiiles, etc) or moving to a chaper provider like DO.
