### ISSUE TITLE
Strict compliance

### ISSUE THREAD

**Issue by NickBurnett** [acmutd/acm-bot#31]
In an attempt to follow convention a bit tighter, we'll switch back to strict-mode in TypeScript. There are a few bugs that are non-strict-compliant so we'll need to refactor those. I'm unsure how much refactoring will have to take place but it will certainly not be to the extent of the original refactor. Maybe a slight system change at most.

**Comment by WillieCubed** [comment]
Status on this?

**Comment by NickBurnett** [comment]
Once I have a chance to take a look at the codebase with @ez314, soon.
