### ISSUE TITLE
Move .shoutout to slash command

### ISSUE THREAD

**Issue by ez314** [acmutd/acm-bot#57]
.shoutout behavior is weird rn because of its long string argument. Because of the way args are parsed from command strings, all quotes are special characters. This means you can't use contractions in shoutouts, which is kinda a problem

Making it a slash command will remove parsing ambiguity.

**Comment by NickBurnett** [comment]
@khreate and I finished this.

**Comment by ez314** [comment]
Just FYI

https://github.blog/2013-01-22-closing-issues-via-commit-messages/
Can also link PRs to issues

**Comment by NickBurnett** [comment]
Yes but the PR was merged before the issue xD

**Comment by ez314** [comment]
ah
