### ISSUE TITLE
Implement modal functionalities

### ISSUE THREAD

**Issue by ez314** [acmutd/acm-bot#71]
modals were added to prod discord.js a week ago <https://discordjs.guide/interactions/modals.html>

- [ ] Verification (might as well resolve #65 at the same time)
- [ ] Circle info, like prompting users for the diff btwn #internship-hunting and #internship-prep. This one might be difficult tho unless we can figure out how to use the required component row.
- [ ] Custom report option (low prio, nobody has used this yet)
- [ ] Maybe circle creation? has 6 fields tho and modals only support 5. we can include trivial args in the command itself as a workaround

@NickBurnett pinging you in to keep you in loop on this

**Comment by NickBurnett** [comment]
Cannot believe they have added modal functionality xD Now I can send people a form inquiring about their coping habits 🤔
